# A bare-bones deployment for Calibre Content Server on Kubernetes
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: calibre-content-server
    labels:
        app.kubernetes.io/name: calibre-content-server
spec:
    strategy:
        type: Recreate
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: calibre-content-server
    template:
        metadata:
            labels:
                app.kubernetes.io/name: calibre-content-server
        spec:
            containers:
                - name: calibre-content-server
                  image: ghcr.io/kquinsland/calibre-content-server-container:your-tag-here
                  imagePullPolicy: IfNotPresent
                  command:
                      - /opt/calibre/calibre-server
                  args:
                      # Don't need bonjour from within the cluster
                      - --disable-use-bonjour
                      # By default, the library is read-only if no users are set up.
                      # Note: this file needs to exist ahead of time. See the user management section of the README
                      - --userdb=/library/users.db
                      - --enable-auth
                      # Adjust this as needed depending on how your volume mount(s) are set up.
                      - /library

                  ports:
                      # API and web interface both served over http
                      - name: http
                        containerPort: 8080
                        protocol: TCP

                  volumeMounts:
                      # This is essentially equivalent to
                      #  -v /some/path/to/your/calibre/library:/library
                      - mountPath: /library
                        name: content-root

                  # Adjust as needed. These values may already be overkill for a small deployment with a few occasional users.
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "512m"

            volumes:
                - name: content-root
                  # OR persistentVolumeClaim or local or nfs ... etc
                  hostPath:
                      path: /some/path/to/your/calibre/library
