---
apiVersion: v1
kind: Service
metadata:
    name: calibre-content-server
    labels:
        app.kubernetes.io/name: calibre-content-server
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: http
    selector:
        app.kubernetes.io/name: calibre-content-server
