---
name: Build and Push Container

on:
    # For manual trigger if needed
    workflow_dispatch:
    release:
      types: [published]

jobs:
    release-package:
      name: Build and Push Container
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read

      steps:
        - name: Checkout repository
          id: checkout
          uses: actions/checkout@v4
          with:
            persist-credentials: false
            fetch-depth: 0

        - name: Set up Docker Buildx
          id: setup-buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          id: login-ghcr
          # See: https://github.com/docker/login-action/releases
          uses: docker/login-action@v3
          with:
            # See: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
              ghcr.io/${{ github.repository }}

        - name: Build and push
          id: build-push
          uses: docker/build-push-action@v6
          with:
            context: .
            # See: https://docs.docker.com/reference/cli/docker/buildx/build/#platform
            platforms: linux/amd64,linux/arm64

            # Don't build/push on PRs
            push: ${{ github.event_name != 'pull_request' }}

            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              BUILD_DATE=${{ steps.meta.outputs.build_date }}
              VCS_REF=${{ steps.meta.outputs.vcs_ref }}
              VERSION=${{ steps.meta.outputs.version }}
